project:
  type: website
  output-dir: docs

website:
  title: "R Intermediário"
  site-url: "https://brunomontezano.github.io/r-workshop-intermediario/"
  navbar:
    left:
      - href: index.qmd
        text: Página inicial
      - href: materiais.qmd
        text: Materiais recomendados
      - href: aulas_e_laboratorios.qmd
        text: Aulas e laboratórios
  page-footer: 
    left: "Copyright 2023, Bruno Montezano"
    right: 
      - icon: github
        href: https://github.com/brunomontezano
      - icon: house
        href: https://brunomontezano.github.io/
      - icon: envelope
        href: mailto:bmontezano@hcpa.edu.br
      - icon: newspaper
        href: https://lattes.cnpq.br/5680118320056968

format:
  html:
    theme: simplex
    css: styles.css
    toc: false

lang: pt-br



